// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * this is icon on project directory folder of file depend on the language and framework
 */
export interface Icon {
    "name": string;
    "path": string;
    "language": string;
    "extension": string;
    "framework": string;
}
