// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "./types/models.js";

export interface Session {
    "id": string;
    "provider": string;
    "history": types$0.ChatMessage[] | null;
    "last_updated": time$0.Time;

    /**
     * workspace path this session belongs to
     */
    "workspace": string;
}
