// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

/**
 * FileNode represents the metadata schema for files and directories
 */
export interface FileNode {
    /**
     * Masked, deterministic unique identifier
     */
    "id": string;
    "name": string;
    "path": string;

    /**
     * Omitted if directory
     */
    "extension"?: string;

    /**
     * "file" or "directory"
     */
    "type": string;

    /**
     * Language key for editor highlighting
     */
    "lang"?: string;

    /**
     * UI state default
     */
    "expanded": boolean;

    /**
     * Omitted if file
     */
    "children"?: (FileNode | null)[] | null;
    "lastUpdate": time$0.Time;
}
