// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CopyFile(arg1:string,arg2:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function HomeDirectory(arg1:string):Promise<string>;

export function MoveFile(arg1:string,arg2:string):Promise<void>;

export function OpenWorkspaceDialog():Promise<string>;

export function ReadDirectory(arg1:string):Promise<main.FileNode>;

export function ReadFile(arg1:string):Promise<string>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function SaveFile(arg1:any,arg2:string):Promise<void>;
