// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AgentChat(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AgentChat'](arg1, arg2, arg3, arg4);
}

export function CopyFile(arg1, arg2) {
  return window['go']['main']['App']['CopyFile'](arg1, arg2);
}

export function CreateDirectory(arg1) {
  return window['go']['main']['App']['CreateDirectory'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function GetGitCommitDetail(arg1, arg2) {
  return window['go']['main']['App']['GetGitCommitDetail'](arg1, arg2);
}

export function GetGitLog(arg1) {
  return window['go']['main']['App']['GetGitLog'](arg1);
}

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HomeDirectory(arg1) {
  return window['go']['main']['App']['HomeDirectory'](arg1);
}

export function ImageToBase64(arg1) {
  return window['go']['main']['App']['ImageToBase64'](arg1);
}

export function ListIcons() {
  return window['go']['main']['App']['ListIcons']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ListWorkspaceSessions(arg1) {
  return window['go']['main']['App']['ListWorkspaceSessions'](arg1);
}

export function LoadAPIKey(arg1) {
  return window['go']['main']['App']['LoadAPIKey'](arg1);
}

export function LoadConfigFromFile(arg1) {
  return window['go']['main']['App']['LoadConfigFromFile'](arg1);
}

export function LoadOllamaHost() {
  return window['go']['main']['App']['LoadOllamaHost']();
}

export function MoveFile(arg1, arg2) {
  return window['go']['main']['App']['MoveFile'](arg1, arg2);
}

export function OpenWorkspaceDialog() {
  return window['go']['main']['App']['OpenWorkspaceDialog']();
}

export function ReadDirectory(arg1) {
  return window['go']['main']['App']['ReadDirectory'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function ReplaceInFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReplaceInFiles'](arg1, arg2, arg3);
}

export function SaveAPIKey(arg1, arg2) {
  return window['go']['main']['App']['SaveAPIKey'](arg1, arg2);
}

export function SaveConfigToFile(arg1, arg2) {
  return window['go']['main']['App']['SaveConfigToFile'](arg1, arg2);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveOllamaHost(arg1) {
  return window['go']['main']['App']['SaveOllamaHost'](arg1);
}

export function SearchInFiles(arg1, arg2) {
  return window['go']['main']['App']['SearchInFiles'](arg1, arg2);
}
