// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {agent} from '../models';
import {types} from '../models';

export function AgentChat(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function CopyFile(arg1:string,arg2:string):Promise<void>;

export function CreateDirectory(arg1:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function GetSession(arg1:string):Promise<agent.Session>;

export function Greet(arg1:string):Promise<string>;

export function HomeDirectory(arg1:string):Promise<string>;

export function ListSessions():Promise<Array<agent.Session>>;

export function LoadAPIKey(arg1:string):Promise<string>;

export function LoadConfigFromFile(arg1:string):Promise<string>;

export function LoadOllamaHost():Promise<string>;

export function MoveFile(arg1:string,arg2:string):Promise<void>;

export function OpenWorkspaceDialog():Promise<string>;

export function ReadDirectory(arg1:string):Promise<types.FileNode>;

export function ReadFile(arg1:string):Promise<Record<string, any>>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function SaveAPIKey(arg1:string,arg2:string):Promise<void>;

export function SaveConfigToFile(arg1:string,arg2:string):Promise<void>;

export function SaveFile(arg1:any,arg2:string):Promise<void>;

export function SaveOllamaHost(arg1:string):Promise<void>;
