// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ChatMessage {
    "role": string;

    /**
     * string OR []ContentBlock
     */
    "content": any;
}
