// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GitCommit represents a single commit entry
 */
export interface GitCommit {
    "hash": string;
    "author": string;
    "date": string;
    "message": string;
}

/**
 * GitCommitDetail holds full details of a commit
 */
export interface GitCommitDetail {
    "hash": string;
    "author": string;
    "date": string;
    "message": string;
    "files": GitFileChange[] | null;
}

/**
 * GitFileChange represents a file changed in a commit
 */
export interface GitFileChange {
    "path": string;
    "status": string;
    "patch": string;
}

/**
 * ReplaceResult represents the result of a replace operation on one file
 */
export interface ReplaceResult {
    "file": string;
    "success": boolean;
    "error"?: string;
}

/**
 * SearchResult represents a single search match
 */
export interface SearchResult {
    "file": string;
    "line": number;
    "content": string;
}
