// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agent$0 from "./agent/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as icons$0 from "./icons/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "./types/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AgentChat calls the agent with session support
 */
export function AgentChat(sessionID: string, userInput: string, provider: string, model: string): $CancellablePromise<void> {
    return $Call.ByID(3649525256, sessionID, userInput, provider, model);
}

/**
 * CopyFile is the cross-device fallback used by MoveFile
 */
export function CopyFile(src: string, dst: string): $CancellablePromise<void> {
    return $Call.ByID(4189727426, src, dst);
}

export function CreateDirectory(target: string): $CancellablePromise<void> {
    return $Call.ByID(897605136, target);
}

export function DeleteFile(target: string): $CancellablePromise<void> {
    return $Call.ByID(3038426332, target);
}

/**
 * GetGitCommitDetail returns full details of a specific commit
 */
export function GetGitCommitDetail(path: string, hash: string): $CancellablePromise<$models.GitCommitDetail | null> {
    return $Call.ByID(3615275381, path, hash);
}

/**
 * GetGitLog returns the commit history for the workspace
 */
export function GetGitLog(path: string): $CancellablePromise<$models.GitCommit[] | null> {
    return $Call.ByID(3094941481, path);
}

export function GetSession(id: string): $CancellablePromise<agent$0.Session | null> {
    return $Call.ByID(1782625745, id);
}

/**
 * Greet returns a greeting for the given name
 */
export function Greet(name: string): $CancellablePromise<string> {
    return $Call.ByID(146695290, name);
}

export function HomeDirectory(name: string): $CancellablePromise<string> {
    return $Call.ByID(369813189, name);
}

export function ImageToBase64(path: string): $CancellablePromise<string> {
    return $Call.ByID(1962163816, path);
}

/**
 * ListIcons returns the list of available icons
 */
export function ListIcons(): $CancellablePromise<icons$0.Icon[] | null> {
    return $Call.ByID(836311005);
}

export function ListSessions(): $CancellablePromise<(agent$0.Session | null)[] | null> {
    return $Call.ByID(2573987328);
}

export function ListWorkspaceSessions(workspace: string): $CancellablePromise<(agent$0.Session | null)[] | null> {
    return $Call.ByID(2937790079, workspace);
}

/**
 * LoadAPIKey retrieves the key from the OS keyring for backend use
 */
export function LoadAPIKey(name: string): $CancellablePromise<string> {
    return $Call.ByID(1824057162, name);
}

/**
 * LoadConfigFromFile retrieves a specific key from the encrypted binary file
 */
export function LoadConfigFromFile(key: string): $CancellablePromise<string> {
    return $Call.ByID(1254335449, key);
}

/**
 * LoadAPIKey retrieves the key from the OS keyring for backend use
 */
export function LoadOllamaHost(): $CancellablePromise<string> {
    return $Call.ByID(2651132289);
}

export function MoveFile(source: string, destination: string): $CancellablePromise<void> {
    return $Call.ByID(4117543282, source, destination);
}

/**
 * OpenWorkspaceDialog triggers a native folder prompt and returns the selected route string
 */
export function OpenWorkspaceDialog(): $CancellablePromise<string> {
    return $Call.ByID(1688263226);
}

/**
 * ReadDirectory recursively scans the target path and returns a nested tree structure
 */
export function ReadDirectory(rootPath: string): $CancellablePromise<types$0.FileNode | null> {
    return $Call.ByID(3255402808, rootPath);
}

export function ReadFile(target: string): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(3012677587, target);
}

export function RenameFile(name: string, source: string): $CancellablePromise<void> {
    return $Call.ByID(3651910365, name, source);
}

/**
 * ReplaceInFiles replaces text in files matching the search query
 */
export function ReplaceInFiles(path: string, searchText: string, replaceText: string): $CancellablePromise<$models.ReplaceResult[] | null> {
    return $Call.ByID(35131455, path, searchText, replaceText);
}

/**
 * SaveAPIKey receives the key from the frontend and stores it securely
 */
export function SaveAPIKey(name: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(3906707351, name, value);
}

/**
 * SaveConfigToFile updates a specific key-value pair in the encrypted binary file
 */
export function SaveConfigToFile(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(1436926533, key, value);
}

export function SaveFile(data: any, target: string): $CancellablePromise<void> {
    return $Call.ByID(913526606, data, target);
}

/**
 * SaveAPIKey receives the key from the frontend and stores it securely
 */
export function SaveOllamaHost(value: string): $CancellablePromise<void> {
    return $Call.ByID(3087497552, value);
}

/**
 * SearchInFiles searches for text in all files within the workspace directory
 */
export function SearchInFiles(path: string, query: string): $CancellablePromise<$models.SearchResult[] | null> {
    return $Call.ByID(4138168029, path, query);
}
